In [ ]:
# 直接通过pytorch实现的代码，因为没有设置并行，所以只支持单卡训练
import os
		
os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"

In [2]:
import pandas as pd

data = pd.read_csv("./ChnSentiCorp_htl_all.csv")
data

      label                                             review
0         1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1         1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2         1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3         1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4         1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风
...     ...                                                ...
7761      0  尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762      0  盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763      0  看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764      0  我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
7765      0  说实在的我很失望，之前看了其他人的点评后觉得还可以才去的，结果让我们大跌眼镜。我想这家酒店以...

[7766 rows x 2 columns]

In [3]:
data = data.dropna()
data

      label                                             review
0         1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1         1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2         1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3         1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4         1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风
...     ...                                                ...
7761      0  尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762      0  盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763      0  看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764      0  我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
7765      0  说实在的我很失望，之前看了其他人的点评后觉得还可以才去的，结果让我们大跌眼镜。我想这家酒店以...

[7765 rows x 2 columns]

In [4]:
from torch.utils.data import Dataset

class MyDataset(Dataset):

    def __init__(self) -> None:
        super().__init__()
        self.data = pd.read_csv("./ChnSentiCorp_htl_all.csv")
        self.data = self.data.dropna()

    def __getitem__(self, index):
        return self.data.iloc[index]["review"], self.data.iloc[index]["label"]
    
    def __len__(self):
        return len(self.data)

In [5]:
dataset = MyDataset()
for i in range(5):
    print(dataset[i])

('距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较为简单.', np.int64(1))
('商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!', np.int64(1))
('早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。', np.int64(1))
('宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小，但加上低价位因素，还是无超所值的；环境不错，就在小胡同内，安静整洁，暖气好足-_-||。。。呵还有一大优势就是从宾馆出发，步行不到十分钟就可以到梅兰芳故居等等，京味小胡同，北海距离好近呢。总之，不错。推荐给节约消费的自助游朋友~比较划算，附近特色小吃很多~', np.int64(1))
('CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风', np.int64(1))

In [6]:
from torch.utils.data import random_split


trainset, validset = random_split(dataset, lengths=[0.9, 0.1])
len(trainset), len(validset)

(6989, 776)

In [7]:
for i in range(5):
    print(trainset[i])

('酒店还可以，价格在自贡来说稍贵。服务还可以。', np.int64(1))
('服务应该再提升一下．怎么也要符合五星的标准啊', np.int64(1))
('宾馆直接对外的价格是168，携程的价格是160，只便宜8元，有点喜剧', np.int64(0))
('酒店境和服度亦算不,但房空太小~~不宣容太大件行李~~且房格可以~~中餐的心不太好吃~~要改善之~~~~但算平宜~~可接受~~西餐格都很好~~但吃的味道一般且令人等得太耐了~~要改善之~~', np.int64(1))
('相对于长春的物价，这个价格有点贵。条件一般，硬件设施比较普通，没有北京如家的温馨。房子也比较小，希望价格上有些优惠，如果没有优惠，希望携程能联系到长春其他连锁的经济型酒店，有很多条件不错的。', np.int64(0))

In [8]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("hfl/chinese-roberta-wwm-ext")

def collate_func(batch):
    texts, labels = [], []
    for item in batch:
        texts.append(item[0])
        labels.append(item[1])
    inputs = tokenizer(texts, max_length=128, padding="max_length", truncation=True, return_tensors="pt")
    inputs["labels"] = torch.tensor(labels)
    return inputs

d:\miniconda3\envs\PyTorch\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
d:\miniconda3\envs\PyTorch\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in E:\huggingface\models--hfl--chinese-roberta-wwm-ext. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [9]:
from torch.utils.data import DataLoader

trainloader = DataLoader(trainset, batch_size=32, shuffle=True, collate_fn=collate_func)
validloader = DataLoader(validset, batch_size=64, shuffle=False, collate_fn=collate_func)

In [14]:
for train in trainloader:
    for idx, input_ids in enumerate(train['input_ids']):
        print(input_ids, train['labels'][idx])
    break

tensor([ 101, 6983, 2421, 6820,  679, 7231, 8024, 2218, 3221, 2990,  897, 4638,
        1288, 3189, 3952, 1469,  671, 3189, 3952, 1922, 7946,  749, 8013,  102,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(1)
tensor([ 101, 6370, 6579, 7716, 1377, 3797, 5384,  969, 3189, 6983, 2421, 1059,
        3221, 4692, 3301, 1351,  812, 4638, 4157, 6397, 2792, 5636, 8024, 2792,
         809, 8024,  711,  749, 1400, 3341, 4638, 3301, 1351,  812, 3175,  912,
        8024,  738, 6206, 1634, 1126, 1368, 8013, 7716, 1377, 3797, 5384,  969,
        3189, 6983, 2421, 4638, 3302, 1218, 1377,  809, 6432, 3221, 1724, 3215,
         704, 4638, 1073, 5745,  511, 2769, 6370, 6579, 4638, 8208, 8160, 4294,
        1352, 2414, 2791,  113, 4294, 2669,  114, 4507,  754, 2769, 1168, 2421,
        6772, 3241, 2347, 5307, 3187, 2791, 8024, 1048, 6589, 1285, 5277, 1168,
         749, 6498, 1290, 1920, 2414, 2791, 8024, 4507,  754, 2769, 2372,  749,
        2111, 2094, 8024, 6820, 5314, 1048, 6589, 2990,  897,  749,  671, 2476,
        1217, 2414,  511, 3302, 1218, 1447, 6820,  102]) tensor(1)
tensor([ 101, 5018,  671, 3613, 1057,  857, 6421, 6983, 2421, 8024,  671, 6822,
        2421, 2218, 2697, 6230, 2523, 5653, 3302, 8024,  800,  812, 4638, 3302,
        1218, 2523, 1453, 1168, 8026, 2769, 3221, 5632, 2346, 2458, 6756, 1343,
        3180, 3952, 4638, 8024, 3241,  677, 8030, 8939, 8038, 8028, 8569, 4157,
        1914, 2798, 1168, 8024, 6822, 2421, 1168, 1184, 1378,  671, 2845, 1399,
        2099, 8024, 1184, 1378, 4638, 3302, 1218,  782, 1447, 2218, 2523, 4178,
        2658, 8024, 7309, 2769, 2458,  749, 6821,  720, 2218, 4638, 6756, 8024,
         671, 2137, 2523, 5168,  749, 8024, 7649, 1391,  749, 3766, 3300, 8043,
         800,  812, 4638, 7218, 1545,  782, 1447,  678, 7564, 2137, 1296, 4638,
        3198,  952, 2218,  769,  807,  749, 1961,  812, 8024, 2769, 3241,  677,
         833, 1168, 8026, 2400,  684,  769,  807,  102]) tensor(1)
tensor([  101,   125,  3299,  8110,  3189,   857,   749,   671,  1921,  8024,
         2697,  6230,  6820,  1377,   809,   511,  3221,  1044,  1184,   857,
         1762,  3124,  1291,  2161,  7667,  4638,  8024,  6392,  3177,  1922,
         2345,   749,  8024,  1310,  4495,  3340,   816,   738,   679,  1962,
         8024,  2798,  2940,  1168,  1744,  6588,  3341,  4638,   511,   852,
         3221,   817,  3419,   738,  3300,  2345,  6655,  1557,  8024,  3124,
         1291,  9784,  1744,  6588, 10398,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0]) tensor(1)
tensor([ 101, 6848,  749,  702, 1947, 7313, 8024, 7481, 4916,  679, 2207,  511,
        7370,  749, 4510, 6228, 8024, 6163,  934,  726, 1587, 1377, 7357,  511,
        4970, 1912, 3307, 6814, 1343, 4994, 4197, 3221, 3717, 3799, 2238, 7553,
         511,  679, 2970, 1358,  928, 4500, 1305,  511, 2802, 7270, 6854,  752,
        1044, 6432, 6206,  121,  119,  128, 1039,  120, 1146, 7164, 8024, 6821,
        2218, 1916, 1377,  809, 4638,  749, 8024, 5310, 2362, 4638, 3198,  952,
        6820, 6206, 1217, 1369, 1912, 3302, 1218, 6589, 8013, 2832, 6401, 1168,
        5307, 4415, 8024, 2233, 4197, 1440, 6401, 2769, 5143, 5320, 2218, 3221,
        6821,  720, 6392, 2137, 4638, 8024,  679, 5543, 3121,  511, 4684, 1168,
        2769, 6432, 6206, 2832, 6401, 1168, 3867, 1291, 8024, 2798, 7028, 3173,
        3121, 6814,  511,  102,    0,    0,    0,    0]) tensor(0)
tensor([ 101, 2595,  817, 3683, 3683, 6772, 7770, 8024, 1762,  707, 3862, 2247,
         754, 3683, 6772, 1962, 4638, 6983, 2421,  749, 8024, 5439, 6983, 2421,
        5436, 3173,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(1)
tensor([ 101, 2421, 2145, 2791, 2523,  679, 7231, 8024,  855, 5390,  738, 2523,
        1962, 8024, 2218, 1762,  674, 6496, 1814, 5520, 1400, 8024, 3241,  677,
        1168,  674, 6496, 1814, 6859, 7478, 2382, 3175,  912, 8024,  769, 6858,
        2523,  912, 1164,  511,  102,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(1)
tensor([ 101,  857, 6814, 4638, 3297, 2345, 4638, 6983, 2421, 8024, 2577, 4542,
         677, 7481, 4522, 6241, 4638, 1059, 6963, 3221, 6983, 2421, 4638, 2805,
        8024, 6820, 6432, 3221, 6130, 3717, 1546,  671, 4638, 1724, 3215, 5277,
        6983, 2421, 8024, 1157, 6822, 2791, 7313, 4638, 3198,  952, 1765,  677,
        6820, 3300, 4478, 2094, 4649, 8024, 2791, 7313, 2523,  679, 1962, 8024,
        3302, 1218, 2578, 2428,  738, 2523, 2345, 8024, 2238, 2094, 7027, 6820,
        3300,  671, 5500, 1456, 6887,  511, 1086,  738,  679,  833, 1343,  857,
         749,  511,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(0)
tensor([ 101,  124, 3299,  857,  749,  125, 3241,  117, 2697, 6230,  679, 7231,
         117, 3683, 5428, 2592, 6206, 1962,  126, 3299, 6820, 3341,  102,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(1)
tensor([ 101,  791, 1921, 1157, 6842, 4638, 2791, 8024, 3680, 3613,  857, 6821,
        7027, 2697, 6230, 6820, 1377,  809, 8024, 6821, 3613, 1057,  857, 3209,
        3227, 4638, 2697, 6230, 3221, 1107, 8024, 2791, 7313, 1107, 8024, 1920,
        1324, 1107, 8024, 7623, 1324,  738, 1107,  511, 3819, 4074, 3717,  738,
         679, 3221, 2523, 4178,  511, 4692, 3341, 1100, 1921, 6820, 3221, 3297,
        1962,  679,  857,  511,  966, 2533,  671, 2990, 4638, 3221, 3193, 7623,
         679, 7231, 8024, 7478, 2382,  705, 2168, 8024, 5445,  684, 4178, 3698,
        5596, 5596, 4638, 8024, 1469, 7623, 1324, 4638, 1102, 1107, 2501, 2768,
        7831, 3209, 4638, 2190, 4212,  511, 2456, 6379, 8038, 5307, 2382, 2697,
        6230, 5381, 1351, 2190, 6983, 2421, 4638, 6397,  817, 3300,  763,  679,
        5016, 8024, 1400, 3341, 2769, 1355, 4385,  102]) tensor(1)
tensor([ 101, 4692, 4212, 4275, 6230, 2533, 6820, 2923,  679, 7231, 4638, 8024,
        1348, 3221,  125, 3215, 5277, 4638, 8024,  852, 1057,  857,  809, 1400,
        7370,  749, 1400, 2637, 3766, 3300, 1166, 4638, 8024, 2791, 7313, 2923,
        1920,  852, 4958, 4958, 4638, 8024, 3193, 7623, 3221, 3300,  852, 3766,
        3300, 1377,  809, 1391, 4638,  691,  691, 8024, 4384, 1862, 3221, 1962,
         852, 1921, 3698, 1922, 1107, 8024, 2600,  722, 2769,  809, 1400,  679,
         833, 1086,  857, 6929, 7027,  511,  102,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(0)
tensor([ 101, 6821, 1126,  725, 3221, 3736, 7346, 3297, 1962, 4638, 6983, 2421,
         749, 8024, 3300, 2523, 1914, 5439, 1912, 6963,  857, 1762, 6821, 7027,
         511, 2791, 7313, 4638, 1920, 2207, 6820, 1377,  809, 8024, 6163, 7652,
        1469, 6392, 3177, 2697, 6230, 3766, 3300,  758, 3215, 4638, 3403, 1114,
        8024, 5050, 1724, 3215, 6820, 2345,  679, 1914,  511, 3297, 6375,  782,
        1358,  679,  749, 4638, 3221, 6821, 2157, 4638,  977, 6756, 1767, 8024,
        2769, 3221, 1762,  671,  702, 3249, 6858, 4638, 3189, 2094, 1343, 4638,
        8024, 5310, 3362, 6820, 3221, 4821,  677, 3300,  782, 1762, 2161, 7667,
        5310, 2042,  511, 1765,  678, 1765,  677, 6963,  977, 4007,  749, 6626,
        2042, 2155,  782, 4638, 6756, 8024, 5310, 3362, 2769,  812,  857, 2421,
        4638,  782, 6206, 2828, 6756,  977, 1762,  102]) tensor(0)
tensor([  101,  6821,  3221,  2769,   857,  6814,  4638,  3297,  2345,  4638,
         6983,  2421,   511,  1057,   857,  4638,  3198,   952,  2791,  1305,
         3018,  7231,  8024,  3209,  3209,  1372,  6206, 10845,  8020,  6821,
          702,   817,  3419,  2769,   738,  2218,   679,  6432,   749,  8024,
         3418,  3315,   679,   966,  8021,  4638,  2791,  6589,  8024,  2233,
         4197,  6206,   124,   945,  4638,  2852,  7032,   511,   976,   749,
         7564,  2956,  3326,  4197,  1400,  2233,  4197,  5310,  2362,  4638,
         3198,   952,  6432,  3766,   976,  8024,  6206,  2769,   802,  4385,
         8024,  1400,  3341,  2798,  5436,  1139,  1296,  2945,  6432,  3766,
         4692,  1168,   511,  5310,  2362,  4500,   749,  8113,  1146,  7164,
         8024,  5445,   684,  2218,  2769,   671,   702,  1762,  5310,  2362,
          511,  5164,  6206,  1355,  4873,  6432,  1372,  3300,  3146,  3144,
         8020,  1469,  7623,  7667,  4638,   671,  3416,   102]) tensor(0)
tensor([ 101, 1765, 3175, 2626,  974, 8024, 3193, 7623, 1377,  809, 3683, 5401,
        2875, 2521, 2792, 8024, 3302, 1218, 1447, 5162, 6574, 2342, 2345, 8024,
        1780, 1104,  679, 1343, 5018,  753, 6636,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(0)
tensor([ 101, 2582,  720, 4692, 6963, 3221,  702, 6206,  948, 7308, 4638, 2875,
        2521, 2792, 8024, 6006, 4197, 1372, 3300, 8209, 1914, 4638,  817, 3419,
        8024,  852, 6820, 3221,  679,  966,  511,  852, 6821, 3221,  702, 4895,
        3668, 1873, 2523, 6818, 4638,  857, 2792,  511, 2792,  809, 3766, 3300,
        6848, 2885,  511, 2990, 7008, 1343, 3668, 1873, 4638, 3301, 1351, 8024,
        1283,  674,  679, 6206, 1343, 4374, 7377, 6890, 1770, 8013, 8013, 8013,
        4696, 4638, 3221,  702, 2426, 1873,  511,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(0)
tensor([ 101, 8213, 2399, 3300,  857, 6814, 8024, 1728, 6983, 2421, 4638, 3302,
        1218,  510, 2595,  817, 3683, 7770, 8024, 2792,  809, 6821, 3613, 6820,
        3221,  857, 2168, 4659,  511,  679, 1398, 4638, 3221, 6983, 2421, 4638,
        3302, 1218, 2692, 6399, 3291, 7770,  749, 8024, 2145, 2791, 7028, 3173,
        6163,  934, 6814, 8024, 2940,  677, 3890, 3253, 4510, 6228,  510, 2414,
         677, 4500, 1501, 3291, 5653, 3302, 8024, 2697, 6230, 2791, 7313, 6498,
        1290, 3698, 3836,  749,  511,  671, 3517, 6205, 7623, 1324, 3241, 7623,
        7608, 4289, 1348, 1359, 2940,  749, 8024, 3188,  705, 2168, 1348, 1377,
        1366, 8024, 1762, 5838, 2526, 2161,  727, 7339, 4028, 1941, 8024, 2341,
        1046, 1613, 3787, 2641, 2641, 6760, 1220,  704, 8024, 6820, 3300, 6929,
        7319,  727, 5445, 5659, 4638, 1613, 3787,  102]) tensor(1)
tensor([ 101, 1765, 3667, 1377,  809, 8024, 6821, 1920, 3519, 3221, 1546,  671,
        4638,  831, 4157,  749,  511, 2791, 7313, 2207, 8024, 6981, 5390, 5042,
        7358, 8024, 5042, 4684, 3766, 3791, 3819, 4074,  511, 3297, 6206, 1462,
        4638, 3221, 3766, 3300, 3265, 4958, 6444, 8024, 1108, 4638, 6206, 1462,
         511,  679, 6814, 1184, 1378, 3302, 1218, 1447, 2578, 2428, 1377,  809,
         511,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(0)
tensor([ 101, 1765, 4415,  855, 5390, 3300, 4157,  974,  117, 1139, 6121, 7370,
        2802, 6756, 1912,  679, 3221, 2523, 3175,  912,  117, 4895, 1765, 7188,
        4991,  738, 3300, 4157, 6655, 4895,  102,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(1)
tensor([ 101, 6983, 2421,  855, 5390, 1762,  769, 6858, 1282, 2099, 6662, 1366,
        8024, 3302, 1218, 1447,  671, 7309,  676,  679, 4761, 8013, 6421, 6983,
        2421, 1333, 1399, 1373,  784,  720, 1290, 1909, 6983, 2421, 8024,  844,
        6369,  711,  749, 1429, 2471, 7560, 2145, 8024, 6629,  749,  702, 3817,
        1399, 2768,  749,  100, 7440, 3457, 2533,  511,  511,  511,  511,  511,
         100, 8024,  679, 2553,  857, 3634, 2421,  749, 8013,  102,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(0)
tensor([ 101,  857, 6814, 1962, 1914, 3613, 6821, 2157, 6983, 2421,  749, 8024,
         677, 3613, 3341, 1168, 1184, 1378, 8024, 3302, 1218, 1447, 5543, 1114,
        4802, 4638, 2845, 1139, 2769, 4638, 1399, 2099, 8024, 2697, 6230, 2523,
         779, 1147,  511, 1724, 3215, 5277, 2218, 3221,  679,  671, 3416,  511,
        5445,  684, 2496, 1921, 3302, 1218, 1447, 6820, 5314, 2769, 2128, 2961,
         749,  671, 7313, 1555, 1218, 1296, 7313, 8024, 2791, 7313, 2523, 3173,
        8024, 3683, 2769, 6370, 4638, 6206, 1962,  817, 3419, 3766, 1359,  511,
        6432, 3221, 6983, 2421, 3018, 3833, 1220, 8024, 1008, 2769,  812, 6821,
        3416, 4638, 1555, 1218, 2145,  782, 6963, 3300, 3322,  833,  775, 1358,
        8024,  679, 7231,  511,  102,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(1)
tensor([ 101,  671, 5663, 8024, 2600, 4638, 3341, 6432,  679, 1350, 5811, 3805,
         511,  769, 6858,  738,  679, 3221, 4294, 1166,  912, 1164,  511,  809,
        1400,  679,  833, 1762, 1343, 6821, 2157, 6983, 2421,  102,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(0)
tensor([ 101, 3680, 3613,  857, 6821,  702, 6983, 2421, 4638, 3198,  952, 8024,
        2600, 3221, 5314, 2769, 1048, 6589, 1285, 5277, 8024, 2523, 3300, 2692,
        2590,  511, 2791, 7313, 2523, 1962, 8024, 3302, 1218,  738,  679, 7231,
         511,  678, 3613, 3341, 6820,  833,  857, 1762, 6821, 7027,  511,  102,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]) tensor(1)
tensor([ 101, 1157, 2798, 2990, 1168, 4638, 1963, 2157, 2571, 2949, 6983, 2421,
        8024, 2418, 6421, 3221, 1963, 2157, 3918, 1766, 4125, 6756, 4991, 2421,
        8024, 1762, 3934, 3696, 3333, 2207, 1277, 1079,  511,  102,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

In [19]:
next(enumerate(trainloader))

(0,
 {'input_ids': tensor([[ 101,  676,  762,  ...,  856,  763,  102],
         [ 101, 2496, 1921,  ..., 4507,  754,  102],
         [ 101, 6821,  702,  ..., 6230, 2161,  102],
         ...,
         [ 101,  115, 2791,  ...,    0,    0,    0],
         [ 101, 1963, 3362,  ..., 2414, 2160,  102],
         [ 101, 2128, 1059,  ...,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 1, 1, 1],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
         1, 0, 1, 1, 0, 1, 1, 1])})

In [21]:
from torch.optim import Adam

model = AutoModelForSequenceClassification.from_pretrained("hfl/chinese-roberta-wwm-ext")

if torch.cuda.is_available():
    model = model.cuda()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at hfl/chinese-roberta-wwm-ext and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [22]:
optimizer = Adam(model.parameters(), lr=2e-5)

In [23]:
def evaluate():
    model.eval()
    acc_num = 0
    with torch.inference_mode():
        for batch in validloader:
            if torch.cuda.is_available():
                batch = {k: v.cuda() for k, v in batch.items()}
            output = model(**batch)
            pred = torch.argmax(output.logits, dim=-1)
            acc_num += (pred.long() == batch["labels"].long()).float().sum()
    return acc_num / len(validset)

In [24]:
import time

def train(epoch=3, log_step=100):
    global_step = 0
    for ep in range(epoch):
        model.train()
        start = time.time()
        for batch in trainloader:
            if torch.cuda.is_available():
                batch = {k: v.cuda() for k, v in batch.items()}
            optimizer.zero_grad()
            output = model(**batch)
            loss = output.loss.mean()
            loss.backward()
            optimizer.step()
            if global_step % log_step == 0:
                print(f"ep: {ep}, global_step: {global_step}, loss: {loss.item()}")
            global_step += 1
        acc = evaluate()
        print(f"ep: {ep}, acc: {acc}, time: {time.time() - start}")

In [25]:
train()

ep: 0, global_step: 0, loss: 0.6479986310005188
ep: 0, global_step: 100, loss: 0.19430020451545715
ep: 0, global_step: 200, loss: 0.20689454674720764
ep: 0, acc: 0.9007731676101685, time: 56.31743407249451
ep: 1, global_step: 300, loss: 0.1646573543548584
ep: 1, global_step: 400, loss: 0.09281891584396362
ep: 1, acc: 0.925257682800293, time: 56.74451804161072
ep: 2, global_step: 500, loss: 0.006735781207680702
ep: 2, global_step: 600, loss: 0.13861918449401855
ep: 2, acc: 0.894329845905304, time: 56.99183511734009

In [26]:
sen = "我觉得这家酒店不错，饭很好吃！"
id2_label = {0: "差评！", 1: "好评！"}
model.eval()
with torch.inference_mode():
    inputs = tokenizer(sen, return_tensors="pt")
    inputs = {k: v.cuda() for k, v in inputs.items()}
    logits = model(**inputs).logits
    pred = torch.argmax(logits, dim=-1)
    print(f"输入：{sen}\n模型预测结果:{id2_label.get(pred.item())}")

输入：我觉得这家酒店不错，饭很好吃！
模型预测结果:好评！

In [27]:
from transformers import pipeline

model.config.id2label = id2_label
pipe = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0)

Device set to use cuda:0

In [28]:
pipe(sen)

[{'label': '好评！', 'score': 0.9986999034881592}]